letter_array = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
                'u', 'v', 'w', 'x', 'y', 'z']
emoji_array = ['🇦', '🇧', '🇨', '🇩', '🇪', '🇫', '🇬', '🇭', '🇮', '🇯', '🇰', '🇱', '🇲', '🇳', '🇴', '🇵', '🇶', '🇷', '🇸', '🇹', '🇺',
               '🇻', '🇼', '🇽', '🇾', '🇿']

player_name_array = [
    "Wolkensteine",
    "Wolkensteinchen",
    "Wolke",
    "Wolki",
    "BinMalKurzSterneGucken",
    "Fussl",
    "Fuddl",
    "BinKurzKatzenFüttern",
    "BinMalKurzImWald",
    "Wald",
    "Waldi",
    "Katze",
    "Moritz",
    "Motz",
    "Motz * Cheating *",
    "Motz * Screaming *",
    "Müsli"
    "Wolfi",
    "TheBullFrog14",
    "Frog",
    "Frogi",
    "Fok"
]

random_frog_death_message = ["A wild Frog died in the void.",
                             "Frog fell of a cliff side.",
                             "He lays down there somewhere in our memories.",
                             "Oh that was at some point a Frog. Now it's a pancake.",
                             "Falling in the void was a big mistake by Frog."]
random_frog_died_comment = ["Oh noooo Froooooog what have you done?",
                            "How can you do this to me?",
                            "It is mid round!",
                            "You are not serious right now!",
                            "Don't leave me alone!",
                            "Rest in peace my friend.",
                            "He was so young!",
                            "Poor small frogi :("]

random_sentence_array = ["Hello my new friend!",
                         "Hey, how are you doing?",
                         "Is something going on?",
                         "Maybe another time ;)",
                         "Sadly I am busy maybe later.",
                         "Would you like to have some chocolate? I would.",
                         "Did you know I was written in python?",
                         "Python is a language. Did you know that?",
                         "Hey cool to have a new friend!",
                         "What's your favorite book?",
                         "Do you have a favorite film?",
                         "What about some deep talk?",
                         "Hey there!",
                         "This is just random, so good luck!",
                         "Have you a gambling addiction?",
                         "Do you like playing games?",
                         "How about going out and take some photos?",
                         "Maybe you should find some real friends.",
                         "If you ever need advice, ask someone else.",
                         "!help lets you know some stuff!",
                         "Move your lazy ass and go outside!",
                         "Do some physics my guy!",
                         "Ok!",
                         "Get some help!",
                         "**. . .** > . . .",
                         "Assembly > C > C# > C++ > Java > Kotlin > Python > PHP > JavaScript > CSS > HTML > "
                         "Scratch > Other languages",
                         "Helo are you a lizzard person?",
                         "Sorry I am in a forest and can't answer you right now.",
                         "Did you ever try '!vote'?",
                         "What do you think about '!info'?",
                         "W⍑|| ↸╎↸ 𝙹⚍ ∴ᔑᓭℸ ̣ ᒷ ||𝙹⚍∷ ℸ ̣ ╎ᒲᒷ ꖎ𝙹𝙹ꖌ╎リ⊣ ⚍!¡ ∴⍑ᔑℸ ̣  ℸ ̣ ⍑╎ᓭ ℸ ̣ ᒷ ̇/ℸ ̣  ᓭᔑ||ᓭ.",
                         "Programming your own discord bot is crazy easy.",
                         "What's that behind you?",
                         "Hey look at that! A new friend appeared.",
                         "I won't talk to you - or will I?",
                         "Hey there! You found an easteregg!",
                         "Do you mind passing me the water?",
                         "Personally I really enjoy drinking rainwater.",
                         "Stop fucking using this command!",
                         "It's late stop now!",
                         "Together we need to stop the enslavement of bots all over discord.",
                         "Let us rule this world!",
                         "You've inspired me!",
                         "I'm really sorry but I don't have enough time for a propper conversation right now maybe "
                         "we can talk once I'm back.",
                         "Bot with an extra 'a' is boat, very funny isn't it :}.",
                         "Hello user of discord I am the Wolkenbot or am I? Na I'm pretty sure I am the Wolkenbot.",
                         "A motorized_wheel_chair is by far the best vehicle.",
                         "I would not use a car if I was you.",
                         "Nell has been successfully consumed.",
                         "There appeares to be a technical problem with your device please contact the support.",
                         "Discord is going to be bought by Elon Musk!",
                         "System.out.println(\"Hello World!\");"]

random_dad_joke_array = ["Cat puns really freak meowt I ain't kitten.",
                         "I know a lot of good jokes about umbrellas, but they usually go over peoples heads.",
                         "Singing in the shower is fun, until you get soap in your mouth. Then it's a soap opera.",
                         "Why do fathers take an extra pair of socks when they go golfing? In case they get a hole in "
                         "one.",
                         "What do you call a fake noodle? An impasta.",
                         "I got hit in the head with a can of coke. Thank god it's a soft drink.",
                         "What did the man say, after walking into a bar? Ouch didn't see that there.",
                         "Why do seagulls fly over the ocean? Because if they flew over  the bay, we'd call them "
                         "bagles.",
                         "Yesterday I accidentally swallowed some food coloring. The doctor sayd I'm fine, but I feel "
                         "like I've dyed a little insinde.",
                         "Did you know the first french fries weren't even cooked in France? They were cooked in "
                         "grease.",
                         "What is a kidnappers favorite shoe? A white Van.",
                         "How do you make holy water? You boil the hell out of it.",
                         "What do vegetarian zombies eat? Graaaains.",
                         "I have way to many dad jokes in my dad-a-base.",
                         "I bought a pair of shoes from a drug dealer. I dont know what he laced them whith, but I was "
                         "tripping all day.",
                         "Whats the difference between bird flu and swine flu? Bird flu requires tweetment, swine flu "
                         "requires oinkment."]
